/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentFormRuntimeUpdatesRouteImport } from './routes/payment-form/runtime-updates'
import { Route as PaymentFormConfigurationRouteImport } from './routes/payment-form/configuration'
import { Route as PaymentFormCardHolderVerificationRouteImport } from './routes/payment-form/card-holder-verification'
import { Route as ExamplesVerifyCardRouteImport } from './routes/examples/verify-card'
import { Route as ExamplesCheckoutRouteImport } from './routes/examples/checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFormRuntimeUpdatesRoute =
  PaymentFormRuntimeUpdatesRouteImport.update({
    id: '/payment-form/runtime-updates',
    path: '/payment-form/runtime-updates',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaymentFormConfigurationRoute =
  PaymentFormConfigurationRouteImport.update({
    id: '/payment-form/configuration',
    path: '/payment-form/configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaymentFormCardHolderVerificationRoute =
  PaymentFormCardHolderVerificationRouteImport.update({
    id: '/payment-form/card-holder-verification',
    path: '/payment-form/card-holder-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesVerifyCardRoute = ExamplesVerifyCardRouteImport.update({
  id: '/examples/verify-card',
  path: '/examples/verify-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesCheckoutRoute = ExamplesCheckoutRouteImport.update({
  id: '/examples/checkout',
  path: '/examples/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/checkout': typeof ExamplesCheckoutRoute
  '/examples/verify-card': typeof ExamplesVerifyCardRoute
  '/payment-form/card-holder-verification': typeof PaymentFormCardHolderVerificationRoute
  '/payment-form/configuration': typeof PaymentFormConfigurationRoute
  '/payment-form/runtime-updates': typeof PaymentFormRuntimeUpdatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/checkout': typeof ExamplesCheckoutRoute
  '/examples/verify-card': typeof ExamplesVerifyCardRoute
  '/payment-form/card-holder-verification': typeof PaymentFormCardHolderVerificationRoute
  '/payment-form/configuration': typeof PaymentFormConfigurationRoute
  '/payment-form/runtime-updates': typeof PaymentFormRuntimeUpdatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/checkout': typeof ExamplesCheckoutRoute
  '/examples/verify-card': typeof ExamplesVerifyCardRoute
  '/payment-form/card-holder-verification': typeof PaymentFormCardHolderVerificationRoute
  '/payment-form/configuration': typeof PaymentFormConfigurationRoute
  '/payment-form/runtime-updates': typeof PaymentFormRuntimeUpdatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples/checkout'
    | '/examples/verify-card'
    | '/payment-form/card-holder-verification'
    | '/payment-form/configuration'
    | '/payment-form/runtime-updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples/checkout'
    | '/examples/verify-card'
    | '/payment-form/card-holder-verification'
    | '/payment-form/configuration'
    | '/payment-form/runtime-updates'
  id:
    | '__root__'
    | '/'
    | '/examples/checkout'
    | '/examples/verify-card'
    | '/payment-form/card-holder-verification'
    | '/payment-form/configuration'
    | '/payment-form/runtime-updates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesCheckoutRoute: typeof ExamplesCheckoutRoute
  ExamplesVerifyCardRoute: typeof ExamplesVerifyCardRoute
  PaymentFormCardHolderVerificationRoute: typeof PaymentFormCardHolderVerificationRoute
  PaymentFormConfigurationRoute: typeof PaymentFormConfigurationRoute
  PaymentFormRuntimeUpdatesRoute: typeof PaymentFormRuntimeUpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-form/runtime-updates': {
      id: '/payment-form/runtime-updates'
      path: '/payment-form/runtime-updates'
      fullPath: '/payment-form/runtime-updates'
      preLoaderRoute: typeof PaymentFormRuntimeUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-form/configuration': {
      id: '/payment-form/configuration'
      path: '/payment-form/configuration'
      fullPath: '/payment-form/configuration'
      preLoaderRoute: typeof PaymentFormConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-form/card-holder-verification': {
      id: '/payment-form/card-holder-verification'
      path: '/payment-form/card-holder-verification'
      fullPath: '/payment-form/card-holder-verification'
      preLoaderRoute: typeof PaymentFormCardHolderVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/verify-card': {
      id: '/examples/verify-card'
      path: '/examples/verify-card'
      fullPath: '/examples/verify-card'
      preLoaderRoute: typeof ExamplesVerifyCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/checkout': {
      id: '/examples/checkout'
      path: '/examples/checkout'
      fullPath: '/examples/checkout'
      preLoaderRoute: typeof ExamplesCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesCheckoutRoute: ExamplesCheckoutRoute,
  ExamplesVerifyCardRoute: ExamplesVerifyCardRoute,
  PaymentFormCardHolderVerificationRoute:
    PaymentFormCardHolderVerificationRoute,
  PaymentFormConfigurationRoute: PaymentFormConfigurationRoute,
  PaymentFormRuntimeUpdatesRoute: PaymentFormRuntimeUpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
